#!/bin/sh
# This file is a part of the omobus-server-buildscripts project.
# Copyright (c) 2006 - 2017 ak-obs, Ltd. <info@omobus.net>.
# Author: Igor Artemov <i_artemov@ak-obs.ru>.

SLAPD_CONF=/etc/slapd/slapd.conf
SLAPD_USER=openldap
SLAPD_GROUP=openldap

if [ ! -f $SLAPD_CONF ]; then
    echo "slapd-env: mo configuration file was found at $SLAPD_CONF."
    exit 0
fi

PIDFILE=`sed -ne 's/^pidfile[[:space:]]\+\(.\+\)/\1/p' "$SLAPD_CONF"`
DBDIR=`sed -ne 's/^directory[[:space:]]\+\(.\+\)/\1/p' "$SLAPD_CONF"`

if [ -z "$PIDFILE" ]; then
    echo "slapd-env: no pid file defined."
    exit 1
fi

piddir=`dirname "$PIDFILE"`
mkdir -m 755 -p $piddir && chown $SLAPD_USER:$SLAPD_GROUP $piddir

mkdir -m 750 -p $DBDIR && chown $SLAPD_USER:$SLAPD_GROUP $DBDIR
